import { Project } from './types';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: '1',
    code: 'CPX-24-001',
    name: 'New Logistics Hub Construction',
    type: 'CAPEX',
    category: 'Large',
    businessOwner: 'Ops Dept',
    pm: 'Alex Mercer',
    stage: 'Execution',
    startDatePlan: '2024-01-10',
    startDateFact: '2024-01-15',
    endDatePlan: '2025-06-30',
    endDateForecast: '2025-08-15',
    isCriticalPath: true,
    scheduleDeviationDays: 45,
    bac: 500,
    eac: 550,
    costDeviation: -50,
    costReason: 'Material price increase',
    designPercent: 100,
    smrPlan: 45,
    smrFact: 38,
    pnrPercent: 0,
    equipmentPercent: 20,
    pv: 225,
    ev: 190,
    ac: 210,
    cpi: 0.90,
    spi: 0.84,
    riskSchedule: 3,
    riskCost: 2,
    riskContract: 1,
    openIssuesCount: 12,
    changeRequestsCount: 3,
    components: [
      { id: 'c1', name: 'Foundation Sector A', type: 'Construction', progress: 100 },
      { id: 'c2', name: 'Foundation Sector B', type: 'Construction', progress: 85 },
      { id: 'c3', name: 'Steel Framework', type: 'Construction', progress: 20 },
      { id: 'c4', name: 'HVAC Units', type: 'Equipment', progress: 0 },
    ],
    tasks: [
      { id: 't1', title: 'Approve Structural Design', category: 'Engineering', status: 'Done', assignee: 'Eng. Team' },
      { id: 't2', title: 'Pour Concrete Sector B', category: 'Construction', status: 'In Progress', assignee: 'Contractor A' },
      { id: 't3', title: 'Order HVAC Units', category: 'Procurement', status: 'Pending', assignee: 'Procurement Dept' },
    ]
  },
  {
    id: '2',
    code: 'IT-24-042',
    name: 'ERP System Upgrade v2.0',
    type: 'IT',
    category: 'Medium',
    businessOwner: 'Finance',
    pm: 'Sarah Jenkins',
    stage: 'Execution',
    startDatePlan: '2024-03-01',
    startDateFact: '2024-03-01',
    endDatePlan: '2024-12-31',
    endDateForecast: '2024-12-15',
    isCriticalPath: true,
    scheduleDeviationDays: -16,
    bac: 120,
    eac: 115,
    costDeviation: 5,
    costReason: 'Efficiency gains',
    designPercent: 100,
    smrPlan: 60,
    smrFact: 65,
    pnrPercent: 10,
    equipmentPercent: 100,
    pv: 72,
    ev: 78,
    ac: 70,
    cpi: 1.11,
    spi: 1.08,
    riskSchedule: 1,
    riskCost: 1,
    riskContract: 1,
    openIssuesCount: 2,
    changeRequestsCount: 0,
    components: [
      { id: 'c1', name: 'Core Module Dev', type: 'Construction', progress: 90 },
      { id: 'c2', name: 'Server Migration', type: 'Equipment', progress: 100 },
      { id: 'c3', name: 'UAT Testing', type: 'Design', progress: 15 },
    ],
    tasks: [
      { id: 't1', title: 'Finalize API Specs', category: 'Engineering', status: 'Done', assignee: 'Dev Lead' },
      { id: 't2', title: 'User Training Manual', category: 'Design', status: 'In Progress', assignee: 'Tech Writer' },
    ]
  },
  {
    id: '3',
    code: 'HSE-24-101',
    name: 'Safety Automation Sensors',
    type: 'HSE',
    category: 'Small',
    businessOwner: 'HSE Dept',
    pm: 'John Doe',
    stage: 'Planning',
    startDatePlan: '2024-06-01',
    startDateFact: '2024-06-10',
    endDatePlan: '2024-09-30',
    endDateForecast: '2024-10-15',
    isCriticalPath: false,
    scheduleDeviationDays: 15,
    bac: 45,
    eac: 48,
    costDeviation: -3,
    costReason: 'Scope adjustment',
    designPercent: 85,
    smrPlan: 20,
    smrFact: 15,
    pnrPercent: 0,
    equipmentPercent: 50,
    pv: 10,
    ev: 7,
    ac: 8,
    cpi: 0.87,
    spi: 0.70,
    riskSchedule: 2,
    riskCost: 2,
    riskContract: 1,
    openIssuesCount: 4,
    changeRequestsCount: 1,
    components: [],
    tasks: []
  },
  {
    id: '4',
    code: 'CPX-24-005',
    name: 'North Wing Expansion',
    type: 'CAPEX',
    category: 'Large',
    businessOwner: 'Regional Director',
    pm: 'Elena V.',
    stage: 'Feasibility',
    startDatePlan: '2025-01-01',
    startDateFact: '',
    endDatePlan: '2026-01-01',
    endDateForecast: '2026-01-01',
    isCriticalPath: true,
    scheduleDeviationDays: 0,
    bac: 1200,
    eac: 1200,
    costDeviation: 0,
    costReason: '',
    designPercent: 15,
    smrPlan: 0,
    smrFact: 0,
    pnrPercent: 0,
    equipmentPercent: 0,
    pv: 0,
    ev: 0,
    ac: 0,
    cpi: 1,
    spi: 1,
    riskSchedule: 2,
    riskCost: 3,
    riskContract: 3,
    openIssuesCount: 1,
    changeRequestsCount: 0,
    components: [],
    tasks: []
  },
  {
    id: '5',
    code: 'OPX-24-012',
    name: 'Annual Maintenance Program',
    type: 'OPEX',
    category: 'Medium',
    businessOwner: 'Ops Dept',
    pm: 'Mike R.',
    stage: 'Commissioning',
    startDatePlan: '2023-06-01',
    startDateFact: '2023-06-01',
    endDatePlan: '2024-07-01',
    endDateForecast: '2024-08-01',
    isCriticalPath: false,
    scheduleDeviationDays: 30,
    bac: 80,
    eac: 95,
    costDeviation: -15,
    costReason: 'Emergency repairs',
    designPercent: 100,
    smrPlan: 95,
    smrFact: 90,
    pnrPercent: 80,
    equipmentPercent: 100,
    pv: 76,
    ev: 72,
    ac: 90,
    cpi: 0.80,
    spi: 0.94,
    riskSchedule: 2,
    riskCost: 3,
    riskContract: 1,
    openIssuesCount: 5,
    changeRequestsCount: 2,
    components: [],
    tasks: []
  },
];
